% m3makefile for Cocktail reuse, modula-3 version
import ("libm3")

import("m2libs")

% interface("Arguments")

%instantiate and use OrdSets:
include_dir("../generics")
interface("IntForOrdSets")
module("IntSets") % Instantiation: OrdSets->InitSets. 

% Needed by intSets: 
interface("BitNoTable")
module("UnsafeUtils")

Module("Checks")
Module("DynArray")
Module("Errors")
Module("General")
Module("Heap")
Module("Idents")
Module("ReuseIO")
Module("Layout")
Module("Lists")
Module("Memory")
Module("Positions")
Module("Relations")
Module("SetsC")
Module("Sets")
Module("Sort")
Module("Source")
Module("StdIO")
Module("StringMem")
Module("Strings")
Module("System")
Module("Texts")
Module("Times")

Library ("cocktailreuse")
