% m3makefile for Cocktail lalrm3: lalr converted to Modula3. 

import("libm3")
import("reusem3")
import("frontm3")

include_dir("instantiations")

module("ArgCheck")
module("Automaton")
module("Check")
module("Compress")
module("Continue")
module("Debug")
module("Default")
module("Final")
module("GenLang")
module("Gen")
module("Infos")
module("Lookahead")
module("LR")
module("Reduce")

implementation("lalr")
program("lalr")

