% m3makefile for Cocktail ReuseIODrv, modula-3 version
import ("libm3")

import("m2libs")

Module("General")
Module("ReuseIO")
Module("Memory")
Module("System")

implementation("ReuseIODrv")
program ("reuseiodrv")

