% m3makefile for Cocktaill reuse, modula-3 version
import ("libm3")

import("m2libs")

Module("DynArray")
Module("General")
Module("ReuseIO")
Module("Memory")
Module("Sets")
Module("System")

implementation("SetsDrv")
program ("setsdrv")

