#
# Makefile for ./common/src
# RMB modified 92/10/19
#

MC      = m2c
MODULAGENS    =
GENS    =
EXE     = Main
MOCKALIBS = -d ../../reuse/src
MOCKAFLAGS = -noindex -norange

include ../../makefilesrc.include

install_modula:
#       no installation work

clean:
	rm -f *.[dimor]
